services:
  server:
    extends:
      file: compose.base.yaml
      service: .redash
    command: server
    depends_on:
      - postgres
      - redis
    ports:
      - "${REDASH_PORT:-5001}:5000"
      - "5678:5678"
    environment:
      PYTHONUNBUFFERED: 0
  scheduler:
    extends:
      file: compose.base.yaml
      service: .redash
    profiles:
      - e2e
      - local
    command: scheduler
    depends_on:
      - server
  worker:
    extends:
      file: compose.base.yaml
      service: .redash
    profiles:
      - e2e
      - local
    command: worker
    depends_on:
      - server
    environment:
      PYTHONUNBUFFERED: 0
  redis:
    image: redis:7-alpine
    restart: unless-stopped
  postgres:
    image: pgautoupgrade/pgautoupgrade:latest
    ports:
      - "${POSTGRES_PORT:-15432}:5432"
    # The following turns the DB into less durable, but gains significant performance improvements for the tests run (x3
    # improvement on my personal machine). We should consider moving this into a dedicated Docker Compose configuration for
    # tests.
    command: postgres -c fsync=off -c full_page_writes=off -c synchronous_commit=OFF
    restart: unless-stopped
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
  email:
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
    restart: unless-stopped
  cypress:
    ipc: host
    build:
      context: .
      dockerfile: Dockerfile.cypress
    profiles:
      - e2e
    depends_on:
      - server
      - worker
      - scheduler
    environment:
      CYPRESS_baseUrl: http://server:5000
      PERCY_TOKEN: ${PERCY_TOKEN:-""}
      PERCY_BRANCH: ${PERCY_BRANCH:-""}
      PERCY_COMMIT: ${PERCY_COMMIT:-""}
      PERCY_PULL_REQUEST: ${PERCY_PULL_REQUEST:-}
      COMMIT_INFO_BRANCH: ${COMMIT_INFO_BRANCH:-""}
      COMMIT_INFO_MESSAGE: ${COMMIT_INFO_MESSAGE:-""}
      COMMIT_INFO_AUTHOR: ${COMMIT_INFO_AUTHOR:-""}
      COMMIT_INFO_SHA: ${COMMIT_INFO_SHA:-""}
      COMMIT_INFO_REMOTE: ${COMMIT_INFO_REMOTE:-""}
      CYPRESS_PROJECT_ID: ${CYPRESS_PROJECT_ID:-""}
      CYPRESS_RECORD_KEY: ${CYPRESS_RECORD_KEY:-""}
      CYPRESS_COVERAGE: ${CYPRESS_COVERAGE:-true}
